services:
  seerr:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 127.0.0.1:5055:5055
    volumes:
      - .:/app:rw,cached
      - /app/node_modules
      - /app/.next
